---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: fail2ban-archlinux
    image: archlinux/base
    pre_build_image: yes
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
  lint:
    name: ansible-lint
    options:
      exclude:
        - meta/version.yml
        - meta/exception.yml
scenario:
  name: archlinux
