---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
lint:
  name: yamllint
driver:
  name: docker
platforms:
  - name: fail2ban-alpine-latest
    image: alpine:latest
    pre_build_image: yes
    command: sh -c "while true ; do sleep 1 ; done"
provisioner:
  name: ansible
  playbooks:
    prepare: ../resources/prepare.yml
    converge: ../resources/playbook.yml
scenario:
  name: alpine-latest
